### ISSUE TITLE
Wiring

### ISSUE THREAD

**Issue by ThauEx** [xSnowHeadx/FakeGPS#2]
Hi,
could you provide the wiring for the audio cable?
The cable shown in the image has tip, ring and sleeve. Where do I connect data, 5V and gnd?
I have a nixie clock from Etsy, but the seller and listing are not available anymore, but it has a port to connect an external gps module. So I want to try this project and maybe I can get it working.

**Comment by xSnowHeadx** [comment]
@ThauEx 
On my clock the tip is +5V, the ring is the GPS signal and the sleeve is ground.
But I'm not sure if your clock has the same connector and if it is compatible with the delivered protocol.

**Comment by ThauEx** [comment]
Thank you, I will open the clock and see if I can see if the wiring is the same.
The protocol should be the same, I think, because it should be some kind of standard. My clock should support the regular gps clock modules with an audio jack connector.

**Comment by ThauEx** [comment]
I checked my clock and it has some labels on the PCB:
Tx, GND and +3.3
Tx is the ring, GND is the sleeve and +3.3 is the tip.
Looks like it's working with 3.3V instead of 5V, as soon as my NodeMCU arrives, I will test a bit.
The 3.3V is to power the nodemcu, right? So no external power source required?

**Comment by xSnowHeadx** [comment]
The +3.3 tip can be connected with the 3V3 pin of the NodeMCU for power supply. I used the VIN pin for the 5V supply. Normally there should no extra power supply be necessary.

**Comment by ThauEx** [comment]
Works like a charm, thank you very much.
